export var menuList = [
    {
        name:'首页',
        icon:'pie-chart',
        url:'index',
        id:1
    },
    {
        name:'pptp账号管理',
        icon:'user',
        id:2,
        children:[
            {
                name:'新开账号',
                url:'open_account',
                id:3
            },
            {
                name:'账号管理',
                url:'account_arrange',
                id:4
            }
        ]
    },
    {
        name:'ip账号管理',
        icon:'team',
        url:'',
        id:5,
        children:[
            {
                name:'使用记录',
                url:'record',
                id:6
            },
            {
                name:'ip白名单',
                url:'white_list',
                id:7
            }
        ]
    },
    {
        name:'财务日志',
        icon:'money-collect',
        url:'',
        id:8,
        children:[
            {
                name:'充值记录',
                url:'recharge_record',
                id:12
            },
            {
                name:'ip记录',
                url:'ip_record',
                id:13
            },
            {
                name:'pptp记录',
                url:'pptp_record',
                id:14
            }
        ]
    },
    {
        name:'账号安全',
        icon:'safety-certificate',
        url:'security',
        id:9
    },
    {
        name:'提交实名',
        icon:'idcard',
        url:'subname',
        id:10
    },
    {
        name:'退出',
        icon:'logout',
        url:'login',
        id:11
    }
]
